"""ingredients attributes

Revision ID: 3edc492da3f9
Revises: fix_safety_level
Create Date: 2025-12-16 09:35:24.648596

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3edc492da3f9'
down_revision: Union[str, Sequence[str], None] = 'fix_safety_level'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('ingredients', sa.Column('max_concentration', sa.Integer(), nullable=True))
    op.add_column('ingredients', sa.Column('carcinogenicity', sa.Integer(), nullable=True))
    op.add_column('ingredients', sa.Column('allergenicity', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('ingredients', 'allergenicity')
    op.drop_column('ingredients', 'carcinogenicity')
    op.drop_column('ingredients', 'max_concentration')
    # ### end Alembic commands ###
